### ISSUE TITLE
Add compatibility for Aplite and Chalk platform

### ISSUE THREAD

**Issue by groyoh** [groyoh/minimalin#31]
- [ ] Aplite
- [x] Chalk

**Comment by groyoh** [comment]
@Dinmas I've seen that you forked the project with an Aplite branch. Do you plan to work on this?

**Comment by Dinmas** [comment]
Hi! I am but I'm still incredibly new to programming in general so it's
more a personal exercise. Would you have any recommendations?

**Comment by groyoh** [comment]
Sounds like a good start. The current implementation should work out of the box as long as the colors are white or black. The biggest part of the work is to update the configuration page and config.js accordingly. There are some rework planned on these component to simplify the workflow though. The way we planned it until now was that aplite would have one dark (background is dark and the rest is white) and light mode (background is white and the rest is black). @AlessioLaiso correct me if in wrong. So instead of all the color choices in the configuration page, there would be a selector for dark/light mode.

**Comment by Dinmas** [comment]
Makes sense. I'm going to be away from my computer for a couple days but I can work on this Monday.

**Comment by Spitemare** [comment]
I know this makes it a bit more difficult, but aplite also now supports GColorDarkGray via dithering. It shows up as white in the emulator but it does work on actual hardware. The difficult part is getting the config page to show just white, black, and gray instead of the full pallette.

The watchface code in this scenario only needs a couple changes to the defaults (GColorDarkGray instead of GColorLightGray, GColorWhite instead of GColorRed) and #ifdef for the rainbow option.

**Comment by Dinmas** [comment]
`Pebble.getActiveWatchInfo().platform` gets sent to the config page so I was thinking to use that to display platform appropriate options on the config page.

**Comment by groyoh** [comment]
@Dinmas I've given some work on the https://github.com/groyoh/minimalin/tree/aplite branch. Maybe you could try it out and give me some feedback?

**Comment by groyoh** [comment]
@Spitemare I don't think we will integrate gray as a choice here, only dark/light mode.

**Comment by groyoh** [comment]
Available in master
